spring.application.name=form
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/formdb?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:tiger}

spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8081}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

frontend.origins=https://form-frontend-blush.vercel.app